name: test

on: [push]

jobs:
  build:

    name: Node.js ${{ matrix.os }} ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.10.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, and yarn test
      run: |
        yarn install
        yarn test
      env:
        CI: true